backend:
  name: test-repo

media_folder: static/assets

collections:
  - name: post
    label: Blog Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { date: date, label: Created At, widget: date }
      - { name: body, label: Post, widget: markdown }
  